--- 
name: Lint Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Filter out ignored files
        run: |
          git ls-files --exclude-standard | xargs -I {} echo "File: {}"
        id: list_files

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint SQL files with SQLFluff
        run: |
          sqlfluff lint --dialect postgres *.sql
